Simplify idea merge patcher script
Use `patch` instead of reinventing the wheel

diff --git a/bin/idea-merge-patcher b/bin/idea-merge-patcher
--- a/bin/idea-merge-patcher
+++ b/bin/idea-merge-patcher
@@ -13,43 +13,23 @@ script_name="${1:-idea}"
 script_path=$(which "$script_name") || ( echo 1>&2 "Unable to locate $script_name" ; exit 1 )
 
 # shellcheck disable=SC2016
-original_contents='declare -a ideargs=()
-declare -- wait=""
+idea_patch='--- idea
++++ idea
+@@ -4,6 +4,10 @@
+ declare -a ideargs=()
+ declare -- wait=""
 
-for o in "$@"; do
-  if [[ "$o" = "--wait" || "$o" = "-w" ]]; then
-    wait="-W"
-    o="--wait"
-  fi
-  if [[ "$o" =~ " " ]]; then
-    ideargs+=("\"$o\"")'
++if [[ "$1" = "merge" ]]; then
++  wait="-W"
++fi
++
+ for o in "$@"; do
+   if [[ "$o" = "--wait" || "$o" = "-w" ]]; then
+     wait="-W"
+'
 
-# shellcheck disable=SC2016
-patched_contents='declare -a ideargs=()
-declare -- wait=""
-
-if [[ "$1" = "merge" ]]; then
-  wait="-W"
-fi
-
-for o in "$@"; do
-  if [[ "$o" = "--wait" || "$o" = "-w" ]]; then
-    wait="-W"'
-
-current_contents=$(tail -n +4 "$script_path" | head -n 10)
-
-if [[ "$current_contents" = "$patched_contents" ]]; then
-  echo 1>&2 "$script_path is already patched"
-  exit 0
-fi
-
-if [[ "$current_contents" != "$original_contents" ]]; then
-  echo 1>&2 "$script_path has unfamiliar contents, cannot patch"
-  exit 2
-fi
-
-new_contents=$(cat <(head -n 3 "$script_path") <(echo "$patched_contents") <(tail -n +10 "$script_path"))
-
-echo "$new_contents" > "$script_path"
-
-echo 1>&2 "$script_path successfully patched"
+(echo "$idea_patch" \
+ | patch --fuzz=0 --silent --no-backup-if-mismatch --forward "$script_path" \
+ && echo 1>&2 "$script_path successfully patched" ) \
+|| (echo 1>&2 "Unable to patch $script_path, it might already be patched, or has unfamiliar contents." \
+    && exit 2)
